import { Request, RequestStatus, RequestType, TurnaroundTier } from '@/types';

export const MOCK_ORG_ID = 'mock-org-crafterkite';
export const MOCK_WORKSPACE_ID = 'mock-ws-marketing';
export const MOCK_USER_ID = 'mock-user-current';

export const MOCK_REQUESTS: Request[] = [
  {
    id: 'req_01',
    orgId: MOCK_ORG_ID,
    workspaceId: MOCK_WORKSPACE_ID,
    title: 'Q4 Brand Campaign — Social Media Assets',
    description: 'Full set of social media assets for the Q4 campaign across Instagram, LinkedIn, and X. Includes static posts, story frames, and animated variants.',
    type: 'DESIGN',
    status: 'IN_PROGRESS',
    priorityOrder: 100,
    turnaroundTier: 'RUSH',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    creatorId: MOCK_USER_ID,
    assigneeId: 'user-maya',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    creator: { id: MOCK_USER_ID, firstName: 'Alex', lastName: 'Rivera', avatarUrl: null },
    assignee: { id: 'user-maya', firstName: 'Maya', lastName: 'Chen', avatarUrl: null },
    workspace: { id: MOCK_WORKSPACE_ID, name: 'Marketing', slug: 'marketing' },
  },
  {
    id: 'req_02',
    orgId: MOCK_ORG_ID,
    workspaceId: MOCK_WORKSPACE_ID,
    title: 'New Product Launch — Hero Banner Design',
    description: 'Hero banner for the homepage announcing the new product. Must align with the updated brand guidelines.',
    type: 'DESIGN',
    status: 'IN_REVISION',
    priorityOrder: 200,
    turnaroundTier: 'PRIORITY',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    creatorId: MOCK_USER_ID,
    assigneeId: 'user-james',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    creator: { id: MOCK_USER_ID, firstName: 'Alex', lastName: 'Rivera', avatarUrl: null },
    assignee: { id: 'user-james', firstName: 'James', lastName: 'Park', avatarUrl: null },
    workspace: { id: MOCK_WORKSPACE_ID, name: 'Product', slug: 'product' },
  },
  {
    id: 'req_03',
    orgId: MOCK_ORG_ID,
    workspaceId: MOCK_WORKSPACE_ID,
    title: 'Annual Report 2024 — Intro Video',
    description: 'A 90-second motion graphic intro for the 2024 Annual Report presentation.',
    type: 'MOTION',
    status: 'SUBMITTED',
    priorityOrder: 300,
    turnaroundTier: 'STANDARD',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    creatorId: MOCK_USER_ID,
    assigneeId: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    creator: { id: MOCK_USER_ID, firstName: 'Alex', lastName: 'Rivera', avatarUrl: null },
    assignee: null,
    workspace: { id: 'ws-exec', name: 'Executive', slug: 'executive' },
  },
  {
    id: 'req_04',
    orgId: MOCK_ORG_ID,
    workspaceId: MOCK_WORKSPACE_ID,
    title: 'Podcast Intro Animation',
    description: 'A short looping animation for the podcast intro screen.',
    type: 'MOTION',
    status: 'COMPLETED',
    priorityOrder: 400,
    turnaroundTier: 'STANDARD',
    dueDate: null,
    creatorId: MOCK_USER_ID,
    assigneeId: 'user-aria',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    creator: { id: MOCK_USER_ID, firstName: 'Alex', lastName: 'Rivera', avatarUrl: null },
    assignee: { id: 'user-aria', firstName: 'Aria', lastName: 'Johnson', avatarUrl: null },
    workspace: { id: 'ws-media', name: 'Media', slug: 'media' },
  },
  {
    id: 'req_05',
    orgId: MOCK_ORG_ID,
    workspaceId: MOCK_WORKSPACE_ID,
    title: 'Email Newsletter — October Edition',
    description: 'Monthly newsletter copy and layout for October. Focus on product updates and team highlights.',
    type: 'COPY',
    status: 'COMPLETED',
    priorityOrder: 500,
    turnaroundTier: 'STANDARD',
    dueDate: null,
    creatorId: MOCK_USER_ID,
    assigneeId: 'user-maya',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    creator: { id: MOCK_USER_ID, firstName: 'Alex', lastName: 'Rivera', avatarUrl: null },
    assignee: { id: 'user-maya', firstName: 'Maya', lastName: 'Chen', avatarUrl: null },
    workspace: { id: MOCK_WORKSPACE_ID, name: 'Marketing', slug: 'marketing' },
  },
  {
    id: 'req_06',
    orgId: MOCK_ORG_ID,
    workspaceId: MOCK_WORKSPACE_ID,
    title: 'Go-to-Market Strategy — SaaS Feature Launch',
    description: 'Comprehensive GTM strategy document for the new AI feature launch in Q1 2025.',
    type: 'STRATEGY',
    status: 'DRAFT',
    priorityOrder: 600,
    turnaroundTier: 'STANDARD',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    creatorId: MOCK_USER_ID,
    assigneeId: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    creator: { id: MOCK_USER_ID, firstName: 'Alex', lastName: 'Rivera', avatarUrl: null },
    assignee: null,
    workspace: { id: 'ws-growth', name: 'Growth', slug: 'growth' },
  },
  {
    id: 'req_07',
    orgId: MOCK_ORG_ID,
    workspaceId: MOCK_WORKSPACE_ID,
    title: 'Onboarding Flow — Frontend Development',
    description: 'Build the new user onboarding flow based on the Figma designs. Must support mobile.',
    type: 'DEVELOPMENT',
    status: 'ACTIVE',
    priorityOrder: 150,
    turnaroundTier: 'RUSH',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    creatorId: MOCK_USER_ID,
    assigneeId: 'user-james',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    creator: { id: MOCK_USER_ID, firstName: 'Alex', lastName: 'Rivera', avatarUrl: null },
    assignee: { id: 'user-james', firstName: 'James', lastName: 'Park', avatarUrl: null },
    workspace: { id: 'ws-engineering', name: 'Engineering', slug: 'engineering' },
  },
];

export const STATUS_LABELS: Record<RequestStatus, string> = {
  DRAFT: 'Draft',
  SUBMITTED: 'Submitted',
  ACTIVE: 'Active',
  IN_PROGRESS: 'In Progress',
  IN_REVISION: 'In Revision',
  COMPLETED: 'Completed',
  ARCHIVED: 'Archived',
};

export const TYPE_LABELS: Record<RequestType, string> = {
  DESIGN: 'Design',
  MOTION: 'Motion',
  COPY: 'Copy',
  STRATEGY: 'Strategy',
  DEVELOPMENT: 'Development',
};

export const TIER_LABELS: Record<TurnaroundTier, string> = {
  STANDARD: 'Standard',
  RUSH: 'Rush',
  PRIORITY: 'Priority',
};
